agents:
  queue: default

common_params:
  plugins:
    - &ci_toolkit
      automattic/a8c-ci-toolkit#5.3.1: ~
    - &docker_plugin
      docker#v5.8.0:
        image: public.ecr.aws/docker/library/ruby:3.2.2
        propagate-environment: true
        environment:
          - RUBYGEMS_API_KEY

steps:
  #################
  # Build and Test
  #################
  - group: "🧪 Build and Test"
    key: build-and-test
    steps:
      - label: "🧪 Build and Test"
        command: |
          echo "--- :rust: Build and Test"
          make build test

  #################
  # Lint
  #################
  - label: ":rubocop: Ruby Lint (Rubocop)"
    command: rubocop
    key: rubocop
    retry:
      manual:
        permit_on_passed: true
    agents:
      queue: linter

  #################
  # Release Binaries
  #################
  - group: "📦 Release Binaries"
    key: release-binaries
    if: build.tag != null
    depends_on:
      - build-and-test
      - rubocop
    steps:
      - label: ":linux: Release Binary (Docker)"
        command: .buildkite/release-binary.sh docker
        plugins: [*ci_toolkit]

      - label: ":apple: Release Binary (Native)"
        command: .buildkite/release-binary.sh native
        plugins: [*ci_toolkit]
        agents:
          queue: mac

  #################
  # Push to RubyGems
  #################
  - label: ":rubygems: Publish to RubyGems"
    key: gem-push
    if: false # temporarily disable Gem publishing // build.tag != null
    depends_on:
     - release-binaries
     - rubocop
    command: .buildkite/gem-push.sh
    plugins: [*docker_plugin]
