agents:
  queue: default

env:
  IMAGE_ID: $IMAGE_ID

common_params:
  plugins:
    - &docker_plugin
      docker#v5.8.0:
        image: public.ecr.aws/docker/library/ruby:3.2.2
        propagate-environment: true
        environment:
          - RUBYGEMS_API_KEY

steps:
  #################
  # Build and Test
  #################
  - group: "Tests"
    key: tests
    steps:
      - label: "🧪 Run Tests"
        command: |
          echo "--- :rust: Run Tests"
          make test

  #################
  # Lint
  #################
  - label: ":rubocop: Ruby Lint (Rubocop)"
    # for now, running in the default queue to avoid the need of a Gemfile the root directory
    command: cd ruby && bundle install && bundle exec rubocop
    key: rubocop
    retry:
      manual:
        permit_on_passed: true
    plugins: [*docker_plugin]

  #################
  # Release Binaries
  #################
  - group: "📦 Release Binaries"
    key: release-binaries
    if: build.tag != null
    depends_on:
      - tests
      - rubocop
    steps:
      - label: ":linux: Release Binary"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y
          source "$$HOME/.cargo/env"

          .buildkite/release-binary.sh native
        plugins: [$CI_TOOLKIT]
        agents:
          queue: android

      - label: ":apple: Release Binary"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y
          source "$$HOME/.cargo/env"

          .buildkite/release-binary.sh native
        plugins: [$CI_TOOLKIT]
        agents:
          queue: mac

  #################
  # Push to RubyGems
  #################
  - label: ":rubygems: Publish to RubyGems"
    key: gem-push
    if: "false" # temporarily disable Gem publishing // build.tag != null
    depends_on:
     - release-binaries
    command: .buildkite/gem-push.sh
    plugins: [*docker_plugin]
